# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'button3.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

  

class Ui_MainWindow(object):

    def call_break_alarm(self):
        f = open("d:\\nikhil python\\eye saver\\notification.txt" , "w")
        k = "1"
        f.write(k)
        f.close()

    def call_face_distance(self):
        f = open("d:\\nikhil python\\eye saver\\face_distance.txt" , "w")
        k = "1"
        f.write(k)
        f.close()      

    def call_blink_detector(self):
        f = open("d:\\nikhil python\\eye saver\\blink_detector.txt" , "w")
        k = "1"
        f.write(k)
        f.close()   

    def off_break_alarm(self):
        f = open("d:\\nikhil python\\eye saver\\notification.txt" , "w")
        k = "0"
        f.write(k)
        f.close()

    def off_face_distance(self):
        f = open("d:\\nikhil python\\eye saver\\face_distance.txt" , "w")
        k = "0"
        f.write(k)
        f.close()

    def off_blink_detector(self):
        f = open("d:\\nikhil python\\eye saver\\blink_detector.txt" , "w")
        k = "0"
        f.write(k)
        f.close()                  

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Break_alarm_button = QtWidgets.QPushButton(self.centralwidget)
        self.Break_alarm_button.setEnabled(True)
        self.Break_alarm_button.setGeometry(QtCore.QRect(530, 260, 251, 121))
        font = QtGui.QFont()
        font.setFamily("Sitka Display Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Break_alarm_button.setFont(font)
        self.Break_alarm_button.setObjectName("Break_alarm_button")
        self.Break_alarm_button.setObjectName("Break_alarm_button")
        self.Break_alarm_button.clicked.connect(self.call_break_alarm)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(260, 30, 271, 111))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.Face_distance_button = QtWidgets.QPushButton(self.centralwidget)
        self.Face_distance_button.setGeometry(QtCore.QRect(270, 260, 251, 121))
        font = QtGui.QFont()
        font.setFamily("Sitka Display Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Face_distance_button.setFont(font)
        self.Face_distance_button.setObjectName("Face_distance_button")
        self.Face_distance_button.clicked.connect(self.call_face_distance)
        self.Blink_detector_button = QtWidgets.QPushButton(self.centralwidget)
        self.Blink_detector_button.setGeometry(QtCore.QRect(10, 260, 251, 121))
        font = QtGui.QFont()
        font.setFamily("Sitka Display Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Blink_detector_button.setFont(font)
        self.Blink_detector_button.setObjectName("Blink_detector_button")
        self.Blink_detector_button.clicked.connect(self.call_blink_detector)
        self.off_break_alarm_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.off_break_alarm_pushButton.setGeometry(QtCore.QRect(600, 390, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.off_break_alarm_pushButton.setFont(font)
        self.off_break_alarm_pushButton.setObjectName("off_break_alarm_pushButton")
        self.off_break_alarm_pushButton.clicked.connect(self.off_break_alarm)
        self.off_face_distance_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.off_face_distance_pushButton.setGeometry(QtCore.QRect(340, 390, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.off_face_distance_pushButton.setFont(font)
        self.off_face_distance_pushButton.setObjectName("off_face_distance_pushButton")
        self.off_face_distance_pushButton.clicked.connect(self.off_face_distance)
        self.off_blink_detector_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.off_blink_detector_pushButton.setGeometry(QtCore.QRect(90, 390, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.off_blink_detector_pushButton.setFont(font)
        self.off_blink_detector_pushButton.setObjectName("off_blink_detector_pushButton")
        self.off_blink_detector_pushButton.clicked.connect(self.off_blink_detector)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Break_alarm_button.setText(_translate("MainWindow", "Break Alarm"))
        self.label.setText(_translate("MainWindow", "EYE SAVER"))
        self.Face_distance_button.setText(_translate("MainWindow", "Face Distance"))
        self.Blink_detector_button.setText(_translate("MainWindow", "Blink Detector"))
        self.off_break_alarm_pushButton.setText(_translate("MainWindow", "off"))
        self.off_face_distance_pushButton.setText(_translate("MainWindow", "off"))
        self.off_blink_detector_pushButton.setText(_translate("MainWindow", "off"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
